### ISSUE TITLE
Checkout does not complete; fails with error

### ISSUE THREAD

**Issue by Seagull-in-Song** [bitpay/ubercart7-plugin#2]
Hi, thanks for offering this.  :)  I'm glad to be able to do a one-click installation (sorta).  

Actually, I'm having a problem with the final portion of the checkout.  Everything went swimmingly right up until the end; I was able to select Bitpay (rather than Paypal, yesss!) as the payment method of choice, but then when I clicked "Review Order" to take me to the next screen, I got the following error message:

"Error
The website encountered an unexpected error. Please try again later."

A look at the log revealed the following entry: 

Location    http://mysite.com/cart/checkout/review
Referrer    http://mysite.com/cart/checkout
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'invoice_id' cannot be null: INSERT INTO {uc_payment_bitpay} (invoice_id, order_id, notify_email, physical, txn_speed) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4); Array ( [:db_insert_placeholder_0] => [:db_insert_placeholder_1] => 63 [:db_insert_placeholder_2] => myemail@gmail.com [:db_insert_placeholder_3] => 0 [:db_insert_placeholder_4] => high ) in uc_payment_method_bitpay() (line 433 of */sites/all/modules/bitpay-ubercart7-plugin-0daf99b/uc_bitpay/uc_bitpay.module).

I was testing this module on a website with the latest versions of Drupal (7.23) and Ubercart (7.x-3.5) installed.  

This guy seems to have had a similar problem: https://drupal.org/node/2116301
(Though I couldn't figure out how to apply it to this case, it deals with a problem he encountered when building a custom checkout display.)

Thanks again, and hope you can help me out.  :)

**Comment by Lythimus** [comment]
I'm using the Apr 23rd build and receiving the same error.
